var_names <- c(
  "lei_code", "year", "name", "country", "esg_score", "esg_combined_score", 
  "esg_controversies_score", "social_pillar_score", "governance_pillar_score", 
  "environmental_pillar_score", "resource_use_score", "emissions_score", 
  "environmental_innovation_score", "workforce_score", "human_rights_score", 
  "community_score", "product_responsibility_score", "management_score", 
  "shareholders_score", "csr_strategy_score", "credit_risk", "credit_valuation", 
  "settlement_risk", "securitisation_exposures", "large_exposures_in_the_trading_book", 
  "operational_risk", "gross_carrying_amount", "cash_balance", 
  "financial_assets_held_for_trading", "financial_assets_at_amortised_cost", 
  "derivatives_hedge_accounting", "fair_value", "total_assets", "cet1", 
  "tier_1_capital_transitional_period", "total_capital_transitional_period", 
  "total_risk_exposure_amount", "cet1_risk_exposure", "tier1_risk_exposure", 
  "totalcap_risk_exposure", "leverage_ratio", "financial_liabilities_held_for_trading", 
  "trading_financial_liabilities1", "financial_liabilities_at_amortised_cost", 
  "provisions", "tax_liabilities", "share_capital_repayable_on_demand", 
  "haircuts", "total_liabilities", "total_equity", "equity_to_assets", 
  "loan_to_assets", "provisions_ratio", "liquidity_ratio", "log_assets", 
  "loan_quality", "rwa_ratio", "esg_quartile", "env_quartile", "soc_quartile", 
  "gov_quartile", "year_factor", "esg_category"
)

var_descriptions <- c(
  "Legal Entity Identifier (unique global identifier for all public and private institutions)",
  "Year of data observation (ranging 2020-2023)",
  "Financial institution name",
  "Country where institution is headquartered",
  "Overall Environmental, Social and Governance performance score",
  "ESG score combined with ESG controversies",
  "Score measuring ESG-related controversies and negative events",
  "Score measuring social responsibility performance",
  "Score measuring corporate governance performance",
  "Score measuring environmental performance",
  "Score measuring company's performance in resource utilization",
  "Score measuring company's emissions reduction initiatives and performance",
  "Score measuring company's capacity for environmental innovation",
  "Score measuring company's commitment to workforce well-being",
  "Score measuring company's human rights compliance and practices",
  "Score measuring company's community engagement and contributions",
  "Score measuring company's product quality, safety, and ethical marketing",
  "Score measuring company's management practices and effectiveness",
  "Score measuring company's treatment of shareholders and ownership structure",
  "Score measuring company's corporate social responsibility strategy",
  "Measure of bank's credit risk exposure, excluding cva",
  "Adjustment for credit valuation",
  "Risk associated with settlement of transactions",
  "Exposure to securitization instruments in banking book after cap",
  "Significant exposures in the trading portfolio",
  "Risk from inadequate internal processes, people, systems, or external events",
  "Total carrying value of balance at central bank and other demand deposits before adjustments",
  "Total cash balance at central bank and other demand deposits",
  "Assets held primarily for trading purposes",
  "Financial assets measured at amortized cost",
  "Derivative instruments used for hedge accounting",
  "Fair value measurement of hedged items in portfolio hedge of interest rate risk",
  "Sum of all assets",
  "Common Equity Tier 1 capital in transitional period",
  "Tier 1 capital during Basel III transitional period",
  "Total regulatory capital during Basel III transitional period",
  "Total risk-weighted assets",
  "CET1 capital as percentage of risk-weighted assets",
  "Tier 1 capital as percentage of risk-weighted assets",
  "Total capital ratio as percentage of risk-weighted assets",
  "Ratio of Tier 1 capital to total exposure",
  "Liabilities held primarily for trading purposes",
  "Alternative measure of trading financial liabilities",
  "Financial liabilities measured at amortized cost",
  "Estimated liabilities with uncertain timing or amount",
  "Deferred and current tax liabilities",
  "Capital that can be withdrawn at shareholder request",
  "Reduction applied to asset value for collateral valuation at fair value",
  "Sum of all liabilities",
  "Total shareholders' equity",
  "Ratio of total equity to total assets",
  "Ratio of loans to total assets",
  "Ratio of provisions to relevant financial measures",
  "Measure of bank's ability to meet short-term obligations",
  "Natural logarithm of total assets (size measure)",
  "Measure of loan portfolio quality",
  "Ratio of risk-weighted assets to total assets",
  "Quartile ranking based on ESG score",
  "Quartile ranking based on environmental pillar score",
  "Quartile ranking based on social pillar score",
  "Quartile ranking based on governance pillar score",
  "Year represented as a factor variable",
  "Categorical classification based on ESG performance"
)

var_sources <- c(
  rep("EBA and LSEG Refinitiv", 4),
  rep("LSEG Refinitiv", 16),
  rep("EBA", 43)
)

# Create the data frame
variables_df <- data.frame(
  "Variable Name" = var_names,
  "Description" = var_descriptions,
  "Source" = var_sources
)